name: 'release'

on:
  push:
    branches:
      - 'main'

permissions:
  contents: 'write'

jobs:
  release:
    uses: rios0rios0/pipelines/.github/workflows/release.yaml@fcc4d3bfbc97b49b7f3f6ccf64f8cc216caf0feb # main
