name: 'release'

on:
  push:
    branches:
      - 'main'

permissions:
  contents: 'write'

jobs:
  release:
    uses: rios0rios0/pipelines/.github/workflows/release.yaml@95f041d824f4bdb71812cb857aedc4a8848304ef # main
