name: 'release'

on:
  push:
    branches:
      - 'main'

permissions:
  contents: 'write'

jobs:
  release:
    uses: rios0rios0/pipelines/.github/workflows/release.yaml@dcde42fda3d5b2045c52e0f4c295390dda2c8270 # main
